// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_chapter_2_completely_clear = "CgkInPOEt5YYEAIQCA"; // <GPGSID>
        public const string achievement_chapter_3_completely_clear = "CgkInPOEt5YYEAIQCg"; // <GPGSID>
        public const string achievement_chapter_5_completely_clear = "CgkInPOEt5YYEAIQDg"; // <GPGSID>
        public const string achievement_the_first_assassination = "CgkInPOEt5YYEAIQAw"; // <GPGSID>
        public const string achievement_chapter_3_normal_clear = "CgkInPOEt5YYEAIQCQ"; // <GPGSID>
        public const string achievement_chapter_1_normal_clear = "CgkInPOEt5YYEAIQBA"; // <GPGSID>
        public const string achievement_chapter_4_completely_clear = "CgkInPOEt5YYEAIQDA"; // <GPGSID>
        public const string achievement_chapter_4_normal_clear = "CgkInPOEt5YYEAIQCw"; // <GPGSID>
        public const string achievement_the_last_assassination = "CgkInPOEt5YYEAIQDw"; // <GPGSID>
        public const string achievement_chapter_1_completely_clear = "CgkInPOEt5YYEAIQBg"; // <GPGSID>
        public const string leaderboard_mission = "CgkInPOEt5YYEAIQBQ"; // <GPGSID>
        public const string achievement_chapter_5_normal_clear = "CgkInPOEt5YYEAIQDQ"; // <GPGSID>
        public const string achievement_chapter_2_normal_clear = "CgkInPOEt5YYEAIQBw"; // <GPGSID>
}

